### ISSUE TITLE
Invalid shebang

### ISSUE THREAD

**Issue by ppattard** [benjaminstout/OSX-KVM#3]
Hello,

I'm using fishshell as a default shell, and calling kvmswitch leads to the following error:
```
Failed to execute process '/Users/xxx/bin/kvmswitch'. Reason:
exec: Exec format error
The file '/Users/xxx/bin/kvmswitch' is marked as an executable but could not be run by the operating system.
```

I found that this is just because of the shebang which is '#/bin/bash' instead of '#!/bin/bash'. I don't know why bash does not complain about this, but to my knowledge shebang should always contain this exclamation mark.

Can you fix it ?

Thank you.

**Comment by ppattard** [comment]
And by the way I forgot to say thank you for the excellent work! Apart from this typo, it works like a charm!

**Comment by stoutput** [comment]
Thanks! Fixed.
