### ISSUE TITLE
Not working on Big Sur

### ISSUE THREAD

**Issue by thomassjy** [benjaminstout/OSX-KVM#4]
This script not working on Big Sur, can you share the detailed steps?

**Comment by kieunam123** [comment]
I bought a usb led keyboard and it requires 'scroll lock' key to turn on led light. 
I'm using Big sur 11.4, at first I thought it was not working but after giving access to terminal by go to 'System Preferences > Security & Privacy > Input Monitoring' and tick on the 'Terminal'
I manually reopen 'kvmswitch' again and a file named 'kvmsled' appear. After that I moved both 2 files to '/Users/your username/bin/' and double-click on 'kvmswitch' . 
Boom. my keyboard lights on :)
